create table if not exists public.progress_snapshots (
  id bigint generated by default as identity primary key,
  progress_date date not null,
  stream integer not null default 0 check (stream between 0 and 418),
  weathered integer not null default 0 check (weathered between 0 and 418),
  heavy integer not null default 0 check (heavy between 0 and 418),
  bsoil integer not null default 0 check (bsoil between 0 and 30),
  created_at timestamptz not null default now()
);

create index if not exists progress_snapshots_created_at_idx
on public.progress_snapshots (created_at desc);

alter table public.progress_snapshots enable row level security;
-- No public policies are required because the app writes through a server route
-- using SUPABASE_SERVICE_ROLE_KEY. Never expose that key to the browser.
